### ISSUE TITLE
Wheels rotate on enable

### ISSUE THREAD

**Issue by AlphaOmegaOLA** [LoganKippnick/2024-MK4i-Neo-Swerve-Template#1]
We're trying to get this working because the code is so simple and this is our first  year with swerve. The wheels spin in the right direction forward and backwards but we seem to be having some steering issues. This is all on the bench. We used Phoenix Tuner X to get the absolute position of each CANcoder and put it in the angle offsets in Constants.java. No matter what values we set, even when we manually tweak them to experiment, the wheels all rotate 30-40 degrees clockwise except for the front right. Is that caused by the PID values? We're unsure if it's just a tuning issue or if something else is wrong.

**Comment by LoganKippnick** [comment]
I believe PID values should be fine. The same ones have worked for a 125 pound robot as well as a bare chassis. This code still isn't perfect yet for the 2024 versions of all the APIs and I'm working with my old team who's using this code to fix these issues. I will get the changes updated into this template and get back to you as soon as I can, hopefully in the next couple of days. One thing that I found with my old team is that the CANcoder readings are actually the wrong direction and we had to tell it CW positive in order to get CCW positive. I'm wondering if your team is having the same issue, hence similar goofy behavior.

**Comment by LoganKippnick** [comment]
Alright. I made a new branch called main-2024.1.1, since I hadn't worked on that template since the beta version of WPILib and I'm not savvy enough with GitHub to merge the separate project it imported into the main branch. I made the changes to that brach that my team made on their code, but I'm still waiting to see if they got it working, since they were having some hardware issues too.

**Comment by GeospatialPython** [comment]
Thank you! That got us REALLY close. We're using the latest CANCoders and firmware and the absolute positions are returned as a float between 0 and 1. We finally realized the code is asking for 0-360 degrees (from the comment and typing - duh) and multiplied times 360. Then things started working much better. Left and right were reversed so we inverted the getLeftX value RobotContainer.java and the left joystick functions worked as expected. The major issue we're having now are the right joystick rotation angle seems to be inverted. We get an "X" pattern instead of a diamond pattern (https://www.chiefdelphi.com/t/swerve-rotation-wheels-pointed-inward/425007). But we haven't found a fix that works yet. We are using the MK4i modules with the Neos on top.

**Comment by LoganKippnick** [comment]
I literally had a shower thought about this like last night lol. Try inverting the steer motors. I believe this is the solution to both problems. This will invert the relative encoder, so make sure that you set the CANcoder direction to match. I believe it will be configured as CCW positive. Please let me know if this fixes it, and I'll update the template code.

**Comment by AlphaOmegaOLA** [comment]
Inverting the steering motors for the win! It drives like a dream. In fact, now we're going to set some current limits to reign it in a little bit. I discovered on Chief Delphi that the wheels jumping sometimes when we enable is a race condition from the CANCoders booting up behind the adjustment. It can be fixed with a timer delay.
